metadata:
  maintainer: Tobias Sterbak (tsterbak)
  device_name: OnePlus Nord N200
  is_ab_device: true
  device_code: dre
  supported_device_codes:
    - dre
    - NordN200
    - OnePlusN200
  additional_steps:
    - dtbo
    - vbmeta
    - vendor_boot
requirements:
  android: 11
steps:
  unlock_bootloader:
    - type: call_button
      content: >
        As a first step, you need to unlock the bootloader. A bootloader is the piece of software, that tells your phone
        how to start and run an operating system (like Android). Your device should be turned on.
        Press 'Confirm and run' to reboot into the bootloader.
      command: adb_reboot_bootloader
    - type: call_button
      content: >
        In this step you actually unlock the bootloader. Just press 'Confirm and run' here. The phone will automatically reboot and reformat.
        Once it's done, press continue here.
      command: fastboot_oem_unlock
    - type: confirm_button
      content: >
        The bootloader is now unlocked. Since the device resets completely, you will need to re-enable Developer Options and USB debugging to continue.
  boot_recovery:
    - type: call_button
      content: >
        Now you need to boot a custom recovery system on the phone. A recovery is a small subsystem on your phone, that manages updating,
        adapting and repairing of the operating system.
        Make sure your device is turned on. You need to reboot into the bootloader again by pressing 'Confirm and run' here. Then continue.
      command: adb_reboot_bootloader
    - type: call_button
      img: twrp-start.jpeg
      content: >
        Boot a custom recovery (temporarily) by pressing 'Confirm and run'. Once it's done continue.
      command: fastboot_boot_recovery
    - type: call_button
      content: >
        In some cases, the inactive slot can be unpopulated or contain much older firmware than the active slot, leading to various issues including a potential hard-brick.
        We can ensure none of that will happen by copying the contents of the active slot to the inactive slot. Press 'confirm and run' to to this. Once you are in the bootloader again, continue.
      command: adb_twrp_copy_partitions
    - type: call_button
      img: twrp-start.jpeg
      content: >
        Now we need to boot into recovery again. Press run and when you see the TWRP screen you can continue.
      command: fastboot_boot_recovery
