metadata:
  maintainer: Allaeddine BOULEFAAT (allaeddineomc)
  device_name: Samsung Galaxy S8
  is_ab_device: false
  device_code: dreamlte
  supported_device_codes:
    - dreamlte
  twrp-link: dreamlte
requirements:
  android: 9.0
steps:
  unlock_bootloader:
  boot_recovery:
    - type: call_button
      content: >
        As a first step, you need to boot into the bootloader. A bootloader is the piece of software, 
        that tells your phone who to start and run an operating system (like Android). Your device should be turned on. 
        Then press 'Confirm and run' to reboot into the bootloader. Continue once it's done.
      command: adb_reboot_download
    - type: call_button
      content: In this step, you need to boot a custom recovery on your device. Press 'Confirm and run' to start the process. Confirm afterwards to continue.
      command: heimdall_flash_recovery
    - type: confirm_button
      img: samsung-buttons-bixby.png
      content: >
        Unplug the USB cable from your device. Then manually reboot into recovery by pressing the *Volume Down* + *Power buttons* for 8~10 seconds 
        until the screen turns black to reboot  & release the buttons immediately when it does, then immediately hold *Volume Up* + *Bixby* + *Power button* until you are in recovery mode.
