metadata:
  maintainer: Tobias Sterbak (tsterbak)
  device_name: Fairphone 3
  is_ab_device: true
  device_code: FP3
  supported_device_codes:
    - FP3
steps:
  unlock_bootloader:
    - type: link_button_with_confirm
      content: >
        As a first step, you need to unlock the bootloader. A bootloader is the piece of software, that tells your phone
        how to start and run an operating system (like Android). Your device should be turned on.
        Click on the button to open the instructions on the Fairphone Support official unlocking website to generate an unlock code for your device.
        Once you've done that, continue.
      link: https://www.fairphone.com/en/bootloader-unlocking-code-for-fairphone-3/
    - type: call_button
      content: >
        Press 'Confirm and run' to reboot into the bootloader.
      command: adb_reboot_bootloader
    - type: call_button
      content: >
        In this step you actually unlock the bootloader. Just press 'Confirm and run' here. Once it's done, press continue here.
      command: fastboot_unlock
    - type: confirm_button
      content: >
        Follow the instructions on the Fairphone screen. This command will wipe all the personal data on your phone.
    - type: call_button
      content: >
        After the phone reboots, boot into the fastboot mode once again by pressing 'Confirm and run' here. Then continue.
      command: adb_reboot_bootloader
    - type: call_button
      content: >
        When you are in fastboot mode again, you need to run another unlock step here.
        Just press 'Confirm and run' here. Once it's done, press continue here.
      command: fastboot_unlock_critical
    - type: confirm_button
      content: >
        Follow the instructions on the Fairphone screen. This command will wipe all the personal data on your phone.
    - type: call_button
      content: >
        To finish the unlocking, the phone needs to reboot. Just press 'Confirm and run' here to reboot. Then continue.
      command: fastboot_reboot
    - type: confirm_button
      content: >
        The bootloader is now unlocked. Since the device resets completely, you will need to re-enable USB debugging to continue.
  boot_recovery:
    - type: confirm_button
      content: >
        Now you need to boot a custom recovery system on the phone. A recovery is a small subsystem on your phone, that manages updating,
        adapting and repairing of the operating system.
    - type: call_button
      content: >
        Turn on your device. Once the device is fully booted, you need to reboot into the bootloader again by pressing 'Confirm and run' here. Then continue.
      command: adb_reboot_bootloader
    - type: call_button
      img: twrp-start.jpeg
      content: >
        Once the device is in fastboot mode, flash the custom recovery (temporarily) by pressing 'Confirm and run'. Once it's done continue.
      command: fastboot_boot_recovery
