metadata:
  maintainer: Tobias Sterbak (tsterbak)
  device_name: Motorola moto g 5G plus / one 5G
  is_ab_device: true
  device_code: nairo 
  supported_device_codes:
    - nairo 
steps:
  unlock_bootloader:
    - type: call_button 
      command: adb_reboot_bootloader
      content: >
        As a first step, you need to unlock the bootloader of your device. A bootloader is the piece of software, that tells your phone
        how to start and run an operating system (like Android). You need to boot into fastboot mode by pressing the 'Confirm and run' button. Then continue.
    - type: call_button 
      command: fastboot_get_unlock_data
      content: >
        Now you need to get your device ID to get an unlock code from Motorola. Press 'Confirm and run' to get the ID. (You need to toggle 'Advanced Output' here to see it.)
        Copy it to a separate file to use it in the next step.
    - type: link_button_with_confirm
      content: >
        Click on the button to open the instructions on Motorola's official unlocking website to generate an unlock code for your bootloader.
        Copy the code from the last step to the website and follow the instructions there. Then continue here.
      link: https://motorola-global-portal.custhelp.com/app/standalone/bootloader/unlock-your-device-a
    - type: confirm_button
      content: Connect the device to your PC via USB. And confirm to continue.
    - type: call_button_with_input
      content: >
        Use your code to unlock the bootloader of your device. Type in the full 21 character code you received by email (Example: 5RTSQCYL7ZJKL4NN35MY). Then confirm an run. Afterwards you can continue.
      command: fastboot_unlock_with_code
    - type: call_button_with_input
      content: >
        You need to perform the last command again, so reenter the code and run again. Afterwards you can continue.
      command: fastboot_unlock_with_code
    - type: call_button
      content: >
        Press the button to reboot. Since the device resets completely, you will need to re-enable USB debugging to continue. 
        Connect your device to your PC via USB. Then confirm here to continue.
      command: fastboot_reboot
  boot_recovery:
    - type: call_button
      content: >
        Now you need to boot a custom recovery system on the phone. A recovery is a small subsystem on your phone, that manages updating,
        adapting and repairing of the operating system.
        Make sure your device is turned on. You need to reboot into the bootloader again by pressing 'Confirm and run' here. Then continue.
      command: adb_reboot_bootloader
    - type: call_button
      content: Boot a custom recovery (temporarily) by pressing 'Confirm and run'. Once it's done continue.
      command: fastboot_boot_recovery
    - type: call_button
      command: adb_twrp_copy_partitions
      content: >
        In some cases, the inactive slot can be unpopulated or contain much older firmware than the active slot, leading to various issues including a potential hard-brick.
        We can ensure none of that will happen by copying the contents of the active slot to the inactive slot. Press 'confirm and run' to to this. Once you are in the bootloader again, continue.
    - type: call_button
      command: fastboot_boot_recovery
      content: >
        Now we need to boot into recovery again. Press run and when you see the TWRP screen you can continue.