metadata:
  maintainer: Tobias Sterbak (tsterbak)/SirRGB
  device_name: Sony Xperia XZ1
  is_ab_device: false
  device_code: poplar
  supported_device_codes:
    - poplar
    - G8341
  twrp-link: poplar
requirements:
  android: 9
steps:
  unlock_bootloader:
    - type: confirm_button
      content: >
        As a first step, you need to unlock the bootloader of your device. On the device, dial *#*#7378423#*#* (*#*#SERVICE#*#*) to launch the service menu.
    - type: confirm_button
      content: >
        Go to service info > configuration and check rooting status - you can only continue if it says 'Bootloader unlock allowed":" Yes.'
    - type: confirm_button
      content: >
        Now go to Settings 'About the phone' and then Status. Write down the IMEI of your device. You will need it in the next step.
    - type: link_button_with_confirm
      content: >
        Click on the button to open the instructions on Sonys official unlocking website to generate an unlock code for your bootloader.
        Once you got the code write it down somewhere and continue to input the code.
      link: https://developer.sony.com/open-source/aosp-on-xperia-open-devices/get-started/unlock-bootloader
    - type: confirm_button
      content: >
        Connect the device to your PC via USB. And confirm to continue.
    - type: call_button
      content: >
        Press the button to reboot into the bootloader now. When the notification light turns blue, confirm to continue.
      command: adb_reboot_bootloader
    - type: call_button_with_input
      content: >
        Use your code to unlock the bootloader of your device. Type in the full 18 character code starting with 0x (Example: 0x3EC4F7AD6E0B32B6).
        If you already did that, you can skip this step.
      command: fastboot_unlock_with_code
    - type: call_button
      content: >
        Press the button to reboot. Since the device resets completely, you will need to re-enable USB debugging to continue.
        Connect your device to your PC via USB. Then confirm here to continue.
      command: fastboot_reboot
  boot_recovery:
    - type: call_button
      content: >
        Now you have to reboot into bootloader again. With your phone turned on, press the button to do so and continue once it is done.
      command: adb_reboot_bootloader
    - type: call_button
      content: >
        Next, you need to boot a custom recovery image. Press the button to flash the selected image. Then continue.
      command: fastboot_flash_boot
