metadata:
  maintainer: Tobias Sterbak (tsterbak)
  devicename: Samsung Galaxy S III Neo
  devicecode: s3ve3g 
steps:
  unlock_bootloader:
  boot_recovery:
    - type: confirm_button
      content: >
        There are two possible hardware configurations of this phone regardless of model number. Some phones were released with a Sony IMX 175 rear camera sensor, while others with a Samsung s5k4h5yb rear camera sensor. As such, we’ve separated this devices builds into two separate builds. The procedure to distinguish which to use is as follows:
        
        - Make sure to be on the latest stock firmware of your variant (you can check updates with Settings, Updates);

        - Make sure the rear camera is working on the stock ROM;

        - Open the phone app and dial *#*#34971539#*#* to access to the hidden menu;
          - Tap on ‘Phone/Cam FW Check’ and take note of the numbers shown in the notification:
          - For E08QT, install the s3ve3gjv builds
          - For B08QT, install the s3ve3gxx builds
        I you are not sure what you used, you can safely restart here and pick the correct image and recovery.
    - type: call_button
      content: >
        As a first step, you need to boot into the bootloader. A bootloader is the piece of software,
        that tells your phone who to start and run an operating system (like Android). Your device should be turned on.
        Then press 'Confirm and run' to reboot into the bootloader. Continue once it's done.
      command: adb_reboot_download
    - type: call_button
      content: >
        In this step, you need to boot a custom recovery on your device.
        Press 'Confirm and run' to start the process. Confirm afterwards to continue.
      command: heimdall_flash_recovery
    - type: confirm_button
      img: samsung-buttons.png
      content: >
        Unplug the USB cable from your device. Then manually reboot into recovery by pressing the *Volume Down* + *Power buttons* for 
        8~10 seconds until the screen turns black & release the buttons immediately when it does, then boot to recovery with the device powered off, 
        hold *Volume Up* + *Home* + *Power*. Confirm when the recovery screen appears.