metadata:
  maintainer: Tobias Sterbak (tsterbak)
  device_name: Pixel 3a
  device_code: sargo 
  supported_device_codes:
    - sargo
requirements:
  android: 12.1.0
steps:
  unlock_bootloader:
    - type: call_button
      content: >
        As a first step, you need to unlock the bootloader. A bootloader is the piece of software, that tells your phone
        how to start and run an operating system (like Android). Your device should be turned on.
        Press 'Confirm and run' to reboot into the bootloader.
      command: adb_reboot_bootloader
    - type: call_button
      content: In this step you actually unlock the bootloader. Just press 'Confirm and run' here. Once it's done, press continue here.
      command: fastboot_unlock
    - type: confirm_button
      content: >
        At this point the device may display on-screen prompts which will require interaction to continue the process of unlocking the bootloader.
        Please take whatever actions the device asks you to to proceed.
    - type: call_button
      content: To finish the unlocking, the phone needs to reboot. Just press 'Confirm and run' here to reboot. Then continue.
      command: fastboot_reboot
    - type: confirm_button
      content: The bootloader is now unlocked. Since the device resets completely, you will need to re-enable Developer Options and USB debugging to continue.
  flash_recovery:
    - type: call_button
      content: >
        Now you need to flash a custom recovery system on the phone. A recovery is a small subsystem on your phone, that manages updating,
        adapting and repairing of the operating system.
        Make sure your device is turned on. You need to reboot into the bootloader again by pressing 'Confirm and run' here. Then continue.
      command: adb_reboot_bootloader
    - type: call_button
      content: Flash a custom recovery (temporarily) by pressing 'Confirm and run'. Once your phone screen looks like the picture on the left, continue.
      command: fastboot_flash_recovery
      img: twrp-start.jpeg